name: DVA_Final_Project
channels:
  - defaults
  - conda-forge
dependencies:
  - scikit-learn
  - jupyter
  - pandas
  - tableauscraper
  - openpyxl
  - xlrd
  - matplotlib
  - rtree
  - pyproj
  - shapely
  - geopandas
